//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ut_ccdronemng_iface_v1.h>
#include <public/ccdronemngtester_iface_v1.h>
#include <public/ccdronemng_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp1
	CEDROOMMessage	comp1Messages[10];
	bool	comp1MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp1QueueNodes[15];
	bool	comp1QueueNodesMarks[15];
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	bool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[14];
	bool	comp2QueueNodesMarks[14];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	bool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[13];
	bool	comp3QueueNodesMarks[13];
 
	public:
 
	UT_CCDroneMng::CEDROOMMemory comp1Memory;
	CCDroneMngTester::CEDROOMMemory comp2Memory;
	CCDroneMng::CEDROOMMemory comp3Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[2];
 
	UT_CCDroneMng   * mp_comp1;
	CCDroneMngTester   * mp_comp2;
	CCDroneMng   * mp_comp3;
 
 
//!Set Components
 
	void SetComponents(UT_CCDroneMng   *p_comp1,
							CCDroneMngTester   *p_comp2,
							CCDroneMng   *p_comp3);
 
 
//Signal Conversion
 
	static TEDROOMSignal C2DroneMngTester_PTesterCtrl__C1MainActor_PTesterCtrl(TEDROOMSignal signal);
	static TEDROOMSignal C1MainActor_PTesterCtrl__C2DroneMngTester_PTesterCtrl(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2DroneMngTester_PDroneCtrl__C3DroneMng_PDroneMngCtrl(TEDROOMSignal signal);
	static TEDROOMSignal C3DroneMng_PDroneMngCtrl__C2DroneMngTester_PDroneCtrl(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	UT_CCDroneMng   * mp_comp1;
	CCDroneMngTester   * mp_comp2;
	CCDroneMng   * mp_comp3;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(UT_CCDroneMng   *p_comp1,
					CCDroneMngTester   *p_comp2,
					CCDroneMng   *p_comp3);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	UT_CCDroneMng::CEDROOMMemory 		* GetComp1Memory(){return &systemMemory.comp1Memory;}
	CCDroneMngTester::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CCDroneMng::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
 
};
#endif
