/*
 * sys_data_pool_ids.h
 *
 *  Created on: Apr 26, 2025
 *      Author: opolo70
 */

#ifndef SERVICE_LIBRARIES_PUS_SERVICES_PUS_SYS_DATA_POOL_INCLUDE_PUBLIC_SYS_DATA_POOL_PIDS_H_
#define SERVICE_LIBRARIES_PUS_SERVICES_PUS_SYS_DATA_POOL_INCLUDE_PUBLIC_SYS_DATA_POOL_PIDS_H_


#define UAH_DRONE_Volt_5V		SYS_DATA_POOL_FIRST_UINT32_PARAM_ID
#define UAH_DRONE_Volt_3_3V		(SYS_DATA_POOL_FIRST_UINT32_PARAM_ID+1)
#define UAH_DRONE_Current_5V 	(SYS_DATA_POOL_FIRST_UINT32_PARAM_ID+2)
#define UAH_DRONE_Current_3_3V 	(SYS_DATA_POOL_FIRST_UINT32_PARAM_ID+3)
#define UAH_DRONE_Temp 			(SYS_DATA_POOL_FIRST_UINT32_PARAM_ID+4)
#define UAH_DRONE_Wind 			(SYS_DATA_POOL_FIRST_UINT32_PARAM_ID+5)


#define UAH_DRONE_OBS_ModeActive	SYS_DATA_POOL_FIRST_UINT8_PARAM_ID

#define UAH_DRONE_X  (SYS_DATA_POOL_FIRST_INT16_PARAM_ID + 0)
#define UAH_DRONE_Y  (SYS_DATA_POOL_FIRST_INT16_PARAM_ID + 1)
#define UAH_DRONE_Z  (SYS_DATA_POOL_FIRST_INT16_PARAM_ID + 2)

#define UAH_DRONE_VX  (SYS_DATA_POOL_FIRST_INT16_PARAM_ID + 3)
#define UAH_DRONE_VY  (SYS_DATA_POOL_FIRST_INT16_PARAM_ID + 4)
#define UAH_DRONE_VZ  (SYS_DATA_POOL_FIRST_INT16_PARAM_ID + 5)




#endif /* SERVICE_LIBRARIES_PUS_SERVICES_PUS_SYS_DATA_POOL_INCLUDE_PUBLIC_SYS_DATA_POOL_PIDS_H_ */
