//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ut_ccdronemng_iface_v1.h>
#include <public/ccdronemngtester_iface_v1.h>
#include <public/ccdronemng_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
int main (void){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	UT_CCDroneMng	comp1(1, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp1Memory());
	CCDroneMngTester	comp2(2, 14, EDROOMprioNormal, 1024, systemDeployment.GetComp2Memory());
	CCDroneMng	comp3(3, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp3Memory());
 
	systemDeployment.Config(&comp1, &comp2, &comp3);
 
	systemDeployment.Start();
 
	return 0;
 
}
