//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/uah_asw_iface_v1.h>
#include <public/cctcmanager_iface_v1.h>
#include <public/cchk_fdirmng_iface_v1.h>
#include <public/ccbkgtcexec_iface_v1.h>
#include <public/ccdronemng_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
int main (void){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	UAH_ASW	comp1(1, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp1Memory());
	CCTCManager	comp2(2, 11, EDROOMprioHigh, 4096, systemDeployment.GetComp2Memory());
	CCHK_FDIRMng	comp3(3, 13, EDROOMprioNormal, 4096, systemDeployment.GetComp3Memory());
	CCBKGTCExec	comp4(4, 10, EDROOMprioNormal, 1024, systemDeployment.GetComp4Memory());
	CCDroneMng	comp5(5, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp5Memory());
 
	systemDeployment.Config(&comp1, &comp2, &comp3, &comp4, &comp5);
 
	systemDeployment.Start();
 
	return 0;
 
}
