//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/uahmarsdrone_iface_v1.h>
#include <public/ccdronemng_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
int main (void){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	UAHMarsDrone	comp1(1, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp1Memory());
	CCDroneMng	comp2(2, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp2Memory());
 
	systemDeployment.Config(&comp1, &comp2);
 
	systemDeployment.Start();
 
	return 0;
 
}
